variable "project_name" {
  description = "Project slug used for resource naming."
  type        = string
}

variable "domain" {
  description = "Resolved root domain for the project."
  type        = string
}

variable "dns_zone_domain" {
  description = "Cloudflare DNS zone domain that contains the project records."
  type        = string
}

variable "gcp_project_id" {
  description = "Google Cloud project ID."
  type        = string
}

variable "gcp_region" {
  description = "Google Cloud region."
  type        = string
  default     = "asia-southeast1"
}

variable "vercel_api_token" {
  description = "Vercel API token."
  type        = string
  sensitive   = true
}

variable "cloudflare_api_token" {
  description = "Cloudflare API token."
  type        = string
  sensitive   = true
  default     = ""
}

variable "cloudflare_account_id" {
  description = "Cloudflare account ID used to look up the managed DNS zone."
  type        = string
  default     = ""
}

variable "manage_cloudflare_dns" {
  description = "Whether Terraform creates Cloudflare DNS records."
  type        = bool
  default     = true
}

variable "upstash_email" {
  description = "Upstash account email."
  type        = string
  default     = ""
}

variable "upstash_api_key" {
  description = "Upstash API key."
  type        = string
  sensitive   = true
  default     = ""
}

variable "redis_url_override" {
  description = "Optional existing Upstash Redis URL. When empty and Redis is required, Terraform provisions Redis."
  type        = string
  sensitive   = true
  default     = ""
}

variable "redis_backend_name" {
  description = "Backend service that receives the managed Redis URL. Empty disables managed Redis."
  type        = string
  default     = ""
}

variable "frontends" {
  description = "Frontend apps to deploy on Vercel."
  type = map(object({
    path               = string
    package            = string
    domain             = string
    build_command      = string
    output_directory   = string
    dns_record_type    = optional(string, "CNAME")
    dns_record_content = optional(string, "cname.vercel-dns.com")
  }))
  default = {}
}

variable "backends" {
  description = "Backend apps to deploy on Cloud Run."
  type = map(object({
    path    = string
    package = string
    domain  = string
    port    = optional(number, 8080)
    image   = optional(string, "")
    env     = optional(map(string), {})
  }))
  default = {}
}

variable "backend_images" {
  description = "Runtime backend container images by backend app name."
  type        = map(string)
  default     = {}
}

variable "runtime_env_vars" {
  description = "Runtime environment variables by service name, generated by @mp-lb/tools-env-mapper."
  type        = map(map(string))
  default     = {}
}

variable "gcp_billing_account" {
  description = "GCP billing account ID for budget alerts."
  type        = string
  default     = ""
}

variable "monthly_budget_usd" {
  description = "Monthly budget limit in USD for alerts."
  type        = number
  default     = 10
}
